### ISSUE TITLE
Missing python-dateutil as package depency for Arch Linux

### ISSUE THREAD

**Issue by HugKitten** [Olivia5k/doge#76]
It gave me this error until I installed python-dateutil:
```
Traceback (most recent call last):
  File "/usr/bin/doge", line 5, in <module>
    from doge.core import main
  File "/usr/lib/python3.12/site-packages/doge/core.py", line 16, in <module>
    from doge import wow
  File "/usr/lib/python3.12/site-packages/doge/wow.py", line 12, in <module>
    import dateutil.easter
```

**Comment by harkabeeparolus** [comment]
Hey, thanks for the report!

I haven't used Arch Linux, and I'm not super well versed in packaging for Linux, but:

- The dependency is clearly declared in the pyproject.toml file, so pip, or any other standards compliant installer, will install it automatically regardless of platform.

- The package seems to be installed into the global system python, according to your debug output, which is generally a bad idea. You should install Python applications into isolated virtual environments (e.g. pipx)

My conclusion:

- It seems to me that Arch isn't packaging this software properly. Whatever manual or automatic process they use for detecting dependencies has failed, and appears not to follow Python standards. I would advise you to report this to the Arch package maintainers.

- I would not recommend installing doge globally into the system Python. I recommend using pipx to install Python based applications safely into their own isolated environments. <https://pipx.pypa.io/>

If you have any other information or suggestions about these issues I would be happy to look into it!

**Comment by harkabeeparolus** [comment]
It appears that [the Arch recipe for doge][arch-doge] uses the [PyPA installer](https://github.com/pypa/installer), which is a low-level tool that does not resolve dependencies. This appears to be how Arch has elected to re-package Python software.

 [arch-doge]: https://gitlab.archlinux.org/archlinux/packaging/packages/doge/-/blob/main/PKGBUILD

This means that every time a Python package changes its dependencies, the Arch recipe must be updated (manually or with automatic tooling) to add or remove any changed dependencies (such as python-dateutil).

This should be reported to the Arch package maintainer, since their recipe is missing a dependency and needs to be fixed.

### Side note

I'm not sure I like this way of redistributing Python packages downstream... Although I suppose it's perhaps safer from a supply chain security perspective.

Do we need to notify Arch every time we change dependencies? Or should we expect every new version to be broken until some end user notifies the downstream maintainers? 🤔 I honestly don't know, and I would like to learn. 😊
